### ISSUE TITLE
yes() / confirmation question: enter 'yes' and ux doesnt help to notice a PEBCAC problem

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [borgbackup/borg#1622]
i am on current master
i entered 

```
$ borg recreate borg/ --chunker-params=default --progress --debug
using builtin fallback logging configuration
29 self tests completed in 0.12 seconds
recreate is an experimental feature.
Type 'YES' if you understand this and want to continue: yes
```

no progress bar or progress indication shows up

**Comment by enkore** [comment]
IIRC it has progress if it processes data, but no progress for metadata processing.

**Comment by RonnyPfannschmidt** [comment]
i noticed that i was entering in lowercase and it never complained

once i corrected it worked

it should print some kind of information on user mistake, absolute silence and not exiting in combination are very confusing

**Comment by ThomasWaldmann** [comment]
It should just abort if the requested string is not entered.

**Comment by enkore** [comment]
Whoops :D Moving it to 1.0.8, since the code wasn't changed and it's probably a problem in yes()

> It should just abort if the requested string is not entered.

Yeah, invalid choice = abort. Ditto if invalid choice was supplied via env-var.

**Comment by ThomasWaldmann** [comment]
yes() can do that all.

the problem was that most clients called it without specifying retry (default: True), but did not give a invalid_msg (so it did not say something is invalid) and no retry_msg (so it did not prompt again).

**Comment by ThomasWaldmann** [comment]
fixed by #1623.

**Comment by kmarius** [comment]
This issue still persists in `master`; the above fix was only merged into the `1.0-maint` branch.

**Comment by ThomasWaldmann** [comment]
@kmarius thanks for the hint, I'll have a look...

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/pull/1623/commits/7b9d0c9739c459066caad9122eb92505d13a6c16

This tells that it is in all releases and also master branch.

@kmarius so, if you have some specific issue, please reopen a new ticket.
