### ISSUE TITLE
coverage tools cause tests fail on head

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#274]
i don't know why Travis hasn't picked this up, but tests fail on my laptop:

```
__________________________________________________ RemoteArchiverTestCase.test_exclude_normalization __________________________________________________

self = <borg.testsuite.archiver.RemoteArchiverTestCase testMethod=test_exclude_normalization>

    def test_exclude_normalization(self):
        self.cmd('init', self.repository_location)
        self.create_regular_file('file1', size=1024 * 80)
        self.create_regular_file('file2', size=1024 * 80)
        with changedir('input'):
            self.cmd('create', '--exclude=file1', self.repository_location + '::test1', '.')
        with changedir('output'):
            self.cmd('extract', self.repository_location + '::test1')
>       self.assert_equal(sorted(os.listdir('output')), ['file2'])
E       AssertionError: Lists differ: ['.coverage.angela.27697.294185', 'file2'] != ['file2']
E
E       First differing element 0:
E       .coverage.angela.27697.294185
E       file2
E
E       First list contains 1 additional elements.
E       First extra element 1:
E       file2
E
E       - ['.coverage.angela.27697.294185', 'file2']
E       + ['file2']

py34/lib/python3.4/site-packages/borg/testsuite/archiver.py:378: AssertionError
```

looks like the codecoverage plugin is screwing things up...

@ThomasWaldmann does that seem familiar to you?

**Comment by ThomasWaldmann** [comment]
try the latest codecov whether it works better, see requirements.d/*

**Comment by anarcat** [comment]
@ThomasWaldmann doing `pip install --upgrade pytest-cov` doesn't fix it.

**Comment by ThomasWaldmann** [comment]
hmm, see the issue tracker there. iirc author said it should be fixed.

**Comment by anarcat** [comment]
i guess you are refering to https://github.com/pytest-dev/pytest-cov/issues/77

it is not fixed - the author suggested a bunch of changes to our test harness, maybe we should deploy that instead...

**Comment by anarcat** [comment]
i tried the changes suggested by the author by merging the changes here:

https://github.com/borgbackup/borg/compare/master...ionelmc:master

but that didn't work: tests still fail.

**Comment by ThomasWaldmann** [comment]
I've seen this effect now and then, but it seemed to only sometimes happen. Do you always have it?

**Comment by anarcat** [comment]
it seems to happen fairly reliably on my laptop, but then again, i couldn't test because tests don't work offline (more on that later :).

**Comment by anarcat** [comment]
i can reproduce this reliably on my laptop, for some reason, not on my desktop. seems like there's a difference in the way the tox env was built? no idea...

**Comment by ThomasWaldmann** [comment]
I didn't see this for quite a while. Close?

**Comment by ThomasWaldmann** [comment]
Seen it again, in some debian powerpc test log.

**Comment by ThomasWaldmann** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=814058 also seen on debian testing infrastructure (see the console.log).

**Comment by ThomasWaldmann** [comment]
Might be interesting to re-test this with 1.1 code (current git master).
There might be different behaviour now due to the move to src/ directory.

**Comment by enkore** [comment]
I've never seen this. Not locally (arch), nor Debian (ppc, Vagrant machines) or one of the BSDs / Solaris.

**Comment by enkore** [comment]
pytest-cov changelog

> 2.2.0 (2015-10-04)
>
>    Added support for changing working directory in tests. Previously changing working directory would disable coverage measurements in suprocesses.

Therefore, closing.
