### ISSUE TITLE
FutureWarning about use_bin_type from msgpack 0.5

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3517]
https://travis-ci.org/borgbackup/borg/jobs/326101482

see the complaints about use_bin_type.

**Comment by ThomasWaldmann** [comment]
this was solved by excluding msgpack 0.5.0.
msgpack 0.5.1 was released and doesn't give the FutureWarning.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/commit/5e007ea7a6f2bbc1da03aac13f16053c2697283e

distributions could adjust the requirements and packages that way. ^
will be like this in next borg release anyway.

**Comment by audeoudh** [comment]
I still have this warning, even with recent version of borg (1.1.4) & msgpack (0.5.4).

```
$ borg info <remote>
Remote: /usr/lib/python3.6/site-packages/msgpack/__init__.py:47: FutureWarning: use_bin_type option is not specified. Default value of the option will be changed in future version.
[…]
```

**Comment by ThomasWaldmann** [comment]
Is msgpack-python < 0.5.0.
And if that warning still happens on the latest version, file a bug at the msgpack project.
