### ISSUE TITLE
Extend initial storage quota

### ISSUE THREAD

**Issue by lucnap** [borgbackup/borg#3948]
How can I extend initial storage quota?
borg init --storage-quota 4G
after some backups I need more space how to have a repository 8G for example?

**Comment by ThomasWaldmann** [comment]
either use `borg config` or carefully edit your `repo/config`.

**Comment by ThomasWaldmann** [comment]
guess this is solved.

**Comment by Ravinou** [comment]
Hello, the `borg config` command or manually editing the config file on the server side does not work in my case. I still have a quota error on the client side. Is there a client side cache to clear?

Thank you!

**Comment by ThomasWaldmann** [comment]
Clientside cache: no (IIRC)

Can you give what you have in your repo config (remove the encryption key, if any)?

**Comment by Ravinou** [comment]
Hi @ThomasWaldmann , I'm currently working on a UI for a central borg repository (that I will publish soon in opensource on my github) so I can give you all the information you ask me because I am in test conditions.

So, in my repo config I have : 

```
[repository]
version = 1
segments_per_dir = 1000
max_segment_size = 524288000
append_only = 0
storage_quota = 1000000000
additional_free_space = 0
id = eecfcbcd81e0cf5850bd9c429f0e6eaa3363d98b7816a3c6ff012f2ec8a24c74
key = XXXXXXXXXXXX
```

I test this command : 
```
borg config /home/XXXX/repo storage_quota 3000000000
```

Now I have this config : 
```
[repository]
version = 1
segments_per_dir = 1000
max_segment_size = 524288000
append_only = 0
storage_quota = 3000000000
additional_free_space = 0
id = eecfcbcd81e0cf5850bd9c429f0e6eaa3363d98b7816a3c6ff012f2ec8a24c74
key = XXXX
```

But when I try to launch a `borg create`I have this : `The storage quota (1.00 GB) has been exceeded (1.01 GB). Try deleting some archives.`

**Comment by ThomasWaldmann** [comment]
Please add the borg version you use.

**Comment by Ravinou** [comment]
borg 1.1.16 on client side and server side.

**Comment by ThomasWaldmann** [comment]
I tried with 1.1.16 and I can't reproduce. If I edit the repo config and increase the quote, it immediately gets reflected by the client.

**Comment by Ravinou** [comment]
What is command on the client ? Did you launch a simple `borgbackup create` like me ?

**Comment by ThomasWaldmann** [comment]
I used `borg create -v --stats REMOTEREPO::archive sourcedir`.

The `-v` will give some addtl. quota info.

**Comment by ThomasWaldmann** [comment]
Are you sure you edit the correct repo config?

**Comment by Ravinou** [comment]
Oh sorry @ThomasWaldmann I just find the solution !!

My software uses the command system in `authorized_keys`.
But my command contains the `--storage-quota` option. **It is this command that is actually important**, and it is logical because it is launched at the user's connection. When I change the option in authorized_keys there is no change in the config file but it is perfectly functional, **good to know**.

I've been working for several days on all these aspects and I had forgotten that I was passing the quota option with the repository restriction here. So I was stubbornly looking for a solution with `borg config` when the solution was in `authorized_keys` because it's my usage...

Really sorry, and a huge thank you for your feedback that allowed me to look elsewhere. 

Hoping that my experience is useful to others :)

Thanks again @ThomasWaldmann ♥

**Comment by ThomasWaldmann** [comment]
Ah, right, that option has higher priority than the repo config. Did not think about it right now either. :-)

**Comment by ThomasWaldmann** [comment]
Maybe you could check the docs whether they somehow mention that.

**Comment by Ravinou** [comment]
While searching the documentation [I found the answer here](https://borgbackup.readthedocs.io/en/stable/internals/data-structures.html#internals-storage-quota)  : "The active quota of a repository is determined by the storage_quota config entry or a **run-time override** (via borg serve)."

But I admit that I had to read between the lines and I would find it more interesting if the "priority" terms came out as you so well said. IMOO

And maybe also an addition here would be interesting: https://borgbackup.readthedocs.io/en/stable/deployment/hosting-repositories.html

Finally, [in this part of the documentation](https://borgbackup.readthedocs.io/en/stable/usage/serve.html), I assume that the term "override" means that the option does have priority over the config. I didn't understand it that way either.

It's my personal opinion on a point of detail in the documentation that led me to the error. But otherwise the documentation of Borg is extremely complete and well done. I always found my answers there :)

**Comment by ThomasWaldmann** [comment]
Guess we both are not native english speakers. Maybe somebody who is can advise on that.

Would the "has priority over" wording be better than "override"?

**Comment by ThomasWaldmann** [comment]
Check #9615.

**Comment by ThomasWaldmann** [comment]
Fix merged into 1.4-maint, does not apply to master.
