### ISSUE TITLE
AttributeError on borg init when run with Python without hard-link support

### ISSUE THREAD

**Issue by willsALMANJ** [borgbackup/borg#4901]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V)

1.1.10

#### Operating system (distribution) and version.

Android / Termux

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg init`

## Describe the problem you're observing.

Thanks to https://github.com/termux/termux-packages/pull/4644, borg is now available in Termux. One issue discovered (and worked around with a patch) might be worth addressing in borg. `borg init` choked trying to do `os.link` because the Termux Python is built without hard-link support. Rather than an `OSError` that `repository.py` has been set up to handle, an `AttributeError` is generated because the `link` function does not even exist in the `os` module.

I think this could be addressed by making the `except` clause in `repository.py` slightly more complex. The benefit would be that `pip install borgbackup` should then also work if all of the required dependencies are installed.

#### Include any warning/errors/backtraces from the system logs

This is copied from the PR linked above:

```
Local Exception
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/borgbackup-1.1.10-py3.8-linux-x86_64.egg/borg/archiver.py", line 4501, in main
    exit_code = archiver.run(args)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/borgbackup-1.1.10-py3.8-linux-x86_64.egg/borg/archiver.py", line 4433, in run
    return set_ec(func(args))
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/borgbackup-1.1.10-py3.8-linux-x86_64.egg/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/borgbackup-1.1.10-py3.8-linux-x86_64.egg/borg/archiver.py", line 280, in do_init
    key = key_creator(repository, args)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/borgbackup-1.1.10-py3.8-linux-x86_64.egg/borg/crypto/key.py", line 110, in key_creator
    return key.create(repository, args)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/borgbackup-1.1.10-py3.8-linux-x86_64.egg/borg/crypto/key.py", line 690, in create
    key.save(target, passphrase)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/borgbackup-1.1.10-py3.8-linux-x86_64.egg/borg/crypto/key.py", line 800, in save
    target.save_key(key_data)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/borgbackup-1.1.10-py3.8-linux-x86_64.egg/borg/repository.py", line 310, in save_key
    self.save_config(self.path, self.config)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/borgbackup-1.1.10-py3.8-linux-x86_64.egg/borg/repository.py", line 292, in save_config
    os.link(config_path, old_config_path)
AttributeError: module 'os' has no attribute 'link'

Platform: Linux localhost 3.18.91-15877854-QB25123770 #1 SMP PREEMPT Mon Jul 29 11:47:47 KST 2019 aarch64
Linux: Unknown Linux  
Borg: 1.1.10  Python: CPython 3.8.0 msgpack: 0.5.6
PID: 839  CWD: /data/data/com.termux/files/home
sys.argv: ['/data/data/com.termux/files/usr/bin/borg', 'init', '--encryption=repokey', './test']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
Oh, I didn't know that there are pythons without `os.link`...

But we can fix that, no problem - do you want to make a PR against master (and later against 1.1-maint)?

**Comment by ThomasWaldmann** [comment]
@willsALMANJ Can you test the PR #4901?

**Comment by ThomasWaldmann** [comment]
TODO: add a unit test.

**Comment by Stunner** [comment]
> @willsALMANJ Can you test the PR #4901?

Do you mean #4903? :)

**Comment by willsALMANJ** [comment]
Hrmm, sorry, I discovered that I can not test this as easily as I would like.

When I try to run `borg init`, I get the error `ImportError: dlopen failed: cannot locate symbol "sync_file_range" refereced by ...borg/platform/linux.cpython-38.so`. Looking in `usr/include/fcntl.h`, I found

```
#if __ANDROID_API__ >= 26
int sync_file_range(...);
#endif
```

My phone uses Android 7 which corresponds to __ANDROID_API__ level 24, so it seems that I need something with at least Android 8 to test. I could try testing in an Android VM if I can't find a newer phone to test with and someone else doesn't test it.

By the way, I get the same error when I use the prebuilt borgbackup Termux package.

To do the test, I did `pkg install liblz4 zstd openssl libacl pkg-config clang` and then `pip install pkgconfig cython` in a virtual environment before running `python setup.py install`. That all appeared to build fine. I discovered that for borg 1.10 it is necessary to set the paths for the required shared libraries with the environment variables like `BORG_OPENSSL_PREFIX` like https://github.com/termux/termux-packages/pull/4644 does, but on master the new usage of `pkgconfig` in `setup.py` works. One other note -- `clang` was needed above for `cython`; in the version of borg packaged for Termux a released version of borg is used which does not need `cython`, so that is why `cython` and `clang` are not referenced in the Termux package's `build.sh`.

**Comment by ThomasWaldmann** [comment]
Yeah, I meant #4903.

**Comment by ThomasWaldmann** [comment]
We also had a sync_file_range issue on Windows Subsystem for Linux (WSL).

Maybe the way master branch deals with that (env var) should be also offered on 1.1-maint (but keeping the automated handler for WSL), so it could be also used on old android.

**Comment by ThomasWaldmann** [comment]
Updated the PR so that the unit tests work on platforms without os.link.

A specific test for borg extracting "hardlinks as copies" is missing still.

**Comment by willsALMANJ** [comment]
Using the `sync.pyx` workaround I mentioned in https://github.com/borgbackup/borg/issues/4905#issuecomment-570302496, I was able to test PR #4903. I was able to create and extract an archive on my system with `os.link`. I observed that `borg init` gave an error before the patch and did not after the patch. I don't understand right now exactly what `handlink_masters` is doing, so I might not have exercised the archive.py change, but I was able to extract files from an archive.

**Comment by ThomasWaldmann** [comment]
Guess the test for that would be to create an archive containing hardlinked files and then try to extract on android. The code in #4903 just extracts the hardlinks as separate, independent files if the platform does not have `os.link`.

**Comment by willsALMANJ** [comment]
I made an attempt at testing the archive.py change. I created a repo on a filesystem with hardlink and copied it to my phone. I found that without this PR I got

```
  File "/data/data/com.termux/files/home/borg/borg/src/borg/archive.py", line 640, in extract_helper                   
    os.link(link_target, path)                                                                                         
AttributeError: module 'os' has no attribute 'link' 
```

as expected. Then with the patch I got a different error:

```
<FD 6>: Permission denied when setting extended attribute security.selinux
Local Exception                                            
Traceback (most recent call last):                                                                                     
  File "/data/data/com.termux/files/home/borg/borg/src/borg/archiver.py", line 4476, in main
    exit_code = archiver.run(args)                                                                                     
  File "/data/data/com.termux/files/home/borg/borg/src/borg/archiver.py", line 4407, in run  
    return set_ec(func(args))                                                                                          
  File "/data/data/com.termux/files/home/borg/borg/src/borg/archiver.py", line 167, in wrapper
    return method(self, args, repository=repository, **kwargs)               
  File "/data/data/com.termux/files/home/borg/borg/src/borg/archiver.py", line 180, in wrapper
    return method(self, args, repository=repository, manifest=manifest, key=key, archive=archive, **kwargs)
  File "/data/data/com.termux/files/home/borg/borg/src/borg/archiver.py", line 809, in do_extract                      
    archive.extract_item(item, stdout=stdout, sparse=sparse, hardlink_masters=hardlink_masters,                        
  File "/data/data/com.termux/files/home/borg/borg/src/borg/archive.py", line 723, in extract_item
    ids = [c.id for c in item.chunks]        
  File "src/borg/item.pyx", line 105, in borg.item.PropDict._make_property._get
AttributeError: attribute chunks not found  
```

There is an selinux message -- I am not sure if that is the problem or just a warning about not being able to copy the selinux attributes (I made the repo with hardlinks on a stock Fedora system with selinux). The repo consisted of two file paths both hardlinked to the same file data. After the error, the extract directory was left with two files. One file had the full content of the original file. The other file was 0 bytes in size.

Maybe this is some other issue and this indicates that the patch at least solves the os.link issues?

**Comment by ThomasWaldmann** [comment]
@willsALMANJ thanks for trying and finding that bug. I think I have fixed that case now in the updated PR code. Can you try again?

The selinux issue can be ignored I guess. Your linux has selinux support, but your android either has not or you do not have the permissions to set them.

**Comment by willsALMANJ** [comment]
Hmm, unfortunately, I still get the same error. It seems like the problem is due to `hardlink_masters` not getting populated, so the

```
            elif chunks is not None:
                # assign chunks to this item, since the item which had the chunks was not extracted
                item.chunks = chunks
```

block in `extract_helper` is not run. I didn't track down where `hardlink_masters` should be getting set though. I checked that `hardlink_masters` is either `None` or `{}` in the debugger.

**Comment by ThomasWaldmann** [comment]
I found the reason and fixed that part of the code, please retry.

**Comment by willsALMANJ** [comment]
It is almost working now. I added in-line comment to the last commit about `hardlink_masters` needing to be `{}` rather than `None` when `has_link` is `False`. I tested with that extra change and I was able to extract my test repo with just a few warnings about not being able to set the security.selinux extended attribute.

**Comment by ThomasWaldmann** [comment]
So the extraction extracted 2 separate files each of correct length and contents then?

**Comment by willsALMANJ** [comment]
Yes, that's right. Two different inodes that `diff` said were equal.

**Comment by ThomasWaldmann** [comment]
Merged into 1.1-maint.

**Comment by ThomasWaldmann** [comment]
TODO: forward port to master.

**Comment by willsALMANJ** [comment]
Is there any particular protocol for porting between the maintenance branches and master, or do you just do it by hand for each patch?

**Comment by ThomasWaldmann** [comment]
cherry-pick, see development section in the docs.
