### ISSUE TITLE
bountysource "borgbackup" organization account issue

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5421]
as this is going on for a while, i guess i'll document it here:

i am admin for the "borgbackup" team (organization) on bountysource, where donations come in from borgbackup users.

i used to be able to create bounties drawing funds from the borgbackup account, but currently this does not work any more.
for "payment options" i only get offered paypal or my personal account, but not the borgbackup team/organization account.

i notified bountysource support about this and they are working on it.

some first attempts with "try to login again", "try deleting cookies/cache" did not help.

i didn't see other org admins complaining publicly yet, thus i assume for now that this is an account specific issue only affecting my / the borgbackup team account.

**Comment by ThomasWaldmann** [comment]
note: currently I also can't create bounties from my personal account, but that is likely because i requested a complete payout (due to decreasing trust in the platform) and thus the available balance on my personal account is 0.

**Comment by ThomasWaldmann** [comment]
@enkore you are also an admin for the "borgbackup" team on bountysource.

Can you try to increase that bounty, drawing USD 50 **from the borgbackup org account** (not: your personal funds)?
- "borgbackup" should be offered under "payment options", additionally to paypal and your personal account.
- "display as" should also be set to "borgbackup" when drawing funds from that account.

https://www.bountysource.com/issues/93368903-implement-borg-mount-with-pyfuse3

**Comment by enkore** [comment]
Works for me (order #123443, shown as borgbackup, backed by borgbackup)

**Comment by enkore** [comment]
Maybe a good time to think about diversifying or moving from BS. There has been quite a bit of motion in this space with Github Sponsors, Tidelift, kofi(?) and so on... something that's somewhat independent from specific issues would probably not hurt considering how much time you are continually investing into borg.

**Comment by ThomasWaldmann** [comment]
@enkore ok, so we know now it is not a fundamental problem with BS orgs, but rather that my personal account somehow got partly decoupled from org.

Other options: Right, guess in the end both models would be good: continuous support for frequently active maintainers, bounties for specific tickets to solve. I started with github sponsors some time ago, but didn't finish it when getting confused about the "organisation" term used there and before the stripe bureaucracy.

**Comment by enkore** [comment]
If you want me to, we could try "turning it off and on again", i.e. removing your account from the org and adding/inviting it back. OTOH there might be a risk that BS doesn't allow the account to be invited/added due to itself being confused about the state.

**Comment by ThomasWaldmann** [comment]
@enkore Let's give their tech support a few days, then we'll try your idea (I'll come back to you when the time has come).

This might be a bug in their code or somewhere, if they find/fix it themselves, maybe that leads to a fix in their code, too.

**Comment by ThomasWaldmann** [comment]
BountySource support is taking rather long. They did not solve it yet...

@enkore kick me out from borgbackup team membership and then add me back / send me an invite again, please.

**Comment by enkore** [comment]
Done!

**Comment by ThomasWaldmann** [comment]
Hmm, I didn't get an invite. Did you just add me without invite?

Also, still no access to org funds, still broken in the same way as before...

**Comment by ThomasWaldmann** [comment]
First email:

Hi ThomasWaldmann,

You have been added as a member of the borgbackup team on Bountysource.

As a member of the borgbackup team, you may be able to take part in a number of activities, according to the permissions that have been set, such as:

    Public - Publicly displayed as a member of borgbackup.
    Developer - Can spend funds that are in the team account.
    Admin - Can add/remove projects and members to the team profile. Can add funds to the team account.

By default, you have the public permission enabled.

Thanks,
The Bountysource Team

**Comment by ThomasWaldmann** [comment]
Second email:



Hi ThomasWaldmann,

Your permissions for borgbackup have been modified by enkore:

    Developer privileges enabled.
    Public visibility enabled.
    Admin access enabled.


Thanks,
The Bountysource Team

**Comment by enkore** [comment]
Invitations only seem to be for people that don't have a BS account, those who do have one, seem to get added immediately.

**Comment by ThomasWaldmann** [comment]
@enkore Before your try, I did invite myself. BS said "invite sent", but I never got an email. So I thought it always works via sending invite / invite acceptance.

**Comment by ThomasWaldmann** [comment]
I did another try inviting myself. Sending the invite email takes about 15 mins, so I first thought "it's not working (again)", but in the end, I got the invitation email.

I have now added another copy of myself as "ThomasWaldmann2", with admin privileges, and from **that** user, I can access borgbackup funds.

The account "ThomasWaldmann" is still not working.

**Comment by ThomasWaldmann** [comment]
works now.
